PLAYLISTS_TO_FILL:
  - name: "Epic - Others - in bulk"  # Non used data, just for you
    uri: spotify:playlist:2NJDGmVyomM1XgQKepq0zV
    artists:
    - name: Stuart Roslyn
      uri: spotify:artist:3SBIwt16v4rnhAd4ZrKH0y
      use_name_instead_of_uri: false
    - name: Harry Lightfoot
      uri: spotify:artist:4bGFHVtFZIw5cyerMJhGSO
      use_name_instead_of_uri: false
    - name: Mike Rubino
      uri: spotify:artist:7wHSUAtaR2NE9GK8KcRpXA
      use_name_instead_of_uri: false
    - name: Kevin Rix
      uri: spotify:artist:6OneC6VqxKoEr5z6N17sOC
      use_name_instead_of_uri: false
    - name: Thomas-Adam Habuda
      uri: spotify:artist:7Hsl8RJNmkcQykhve92ndg
      use_name_instead_of_uri: false
    - name: Samuel Karl Bohn
      uri: spotify:artist:3r0VQkZMwllnNoL3iluIpC
      use_name_instead_of_uri: false
    - name: Axl Rosenberg
      uri: spotify:artist:6SaqzT5DEwSMzed38o5NgA
      use_name_instead_of_uri: false
    - name: Richard Canavan
      uri: spotify:artist:6vib2YLhvpNjhHj6nQeZpF
      use_name_instead_of_uri: false
    - name: Peter Mauder
      uri: spotify:artist:4zWuObRcDD0zwaIrd4QwA2
      use_name_instead_of_uri: false
    - name: Piotr Adam Musiał
      uri: spotify:artist:5xdobesgympJ3RSZC2uNjB
      use_name_instead_of_uri: false
    - name: Ian Arber
      uri: spotify:artist:5RvFRZpYvnzsKpOZM9mkKj
      use_name_instead_of_uri: false
    - name: Steve Porter
      uri: spotify:artist:3OCVxMfzchKw3AUQhLiofw
      use_name_instead_of_uri: false
    - name: Paul Dinletir
      uri: spotify:artist:4WPVihOt93o5MaX3ruQ5dA
      use_name_instead_of_uri: false
    - name: Cody Douglas Still
      uri: spotify:artist:4QbuThyy7qoda1GY8W9Nqi
      use_name_instead_of_uri: false
    - name: Sergiu-Dan Muresan
      uri: spotify:artist:25cJAijAJMJeBfFjncneZP
      use_name_instead_of_uri: false
    - name: Daniel Lozinski
      uri: spotify:artist:0HaRjxym2aUfEv1jzP4KzP
      use_name_instead_of_uri: false
    - name: Kyle Booth
      uri: spotify:artist:0oUzZwAusBiJeqyYQciRuS
      use_name_instead_of_uri: false
    - name: Jochen Flach
      uri: spotify:artist:4VTvhpy2hahccpbZ9IfjRf
      use_name_instead_of_uri: false
    - name: Martyn Corbet
      uri: spotify:artist:1EhCA6gStZjDhj2sbtjQ9Y
      use_name_instead_of_uri: false
    - name: Jeff Marsh
      uri: spotify:artist:3k4brmGcy2XKniTCeYjheD
      use_name_instead_of_uri: false
    - name: Bianca Ban
      uri: spotify:artist:6lSNqL8tjVTaDm1Y2jbzdQ
      use_name_instead_of_uri: false
    - name: Michael Patti
      uri: spotify:artist:69Cz11KzFtiYQ7dV6CKnvx
      use_name_instead_of_uri: false
    - name: Armen Hambar
      uri: spotify:artist:3EMv84Jw9Quywvb5hDd2Yk
      use_name_instead_of_uri: false
    - name: Vlado Hudec
      uri: spotify:artist:0NAFI1sFmTGYi467Vv9SwN
      use_name_instead_of_uri: false
    - name: Aram Mandossian
      uri: spotify:artist:78lHyg96k1Lwp0hegQWLAA
      use_name_instead_of_uri: false
    - name: Jo Blankenburg
      uri: spotify:artist:4tuiQRw9bC9HZhSFJEJ9Mz
      use_name_instead_of_uri: false
    - name: Logan Epic Canto
      uri: spotify:artist:4Q8MR3f7fJ6OiuQpP1PS62
      use_name_instead_of_uri: false
    - name: Iliya Zaki & Alexey Soloviev
      uri: spotify:artist:5vw740fs74gAneTG7scsYK
      use_name_instead_of_uri: false
    - name: Dmitriy Poluhtin
      uri: spotify:artist:3HNVDJqX87GPpTBk1K3n49
      use_name_instead_of_uri: false
    - name: Sergey Zubarev
      uri: spotify:artist:4qCQpIhMA3A7p5q9n1DIky
      use_name_instead_of_uri: false
    - name: Christian Fernando Perucchi
      uri: spotify:artist:7sRGgcP561VC3uURQavCCJ
      use_name_instead_of_uri: false
    - name: Rally Wender
      uri: spotify:artist:7B9st1Twe6xVCGQ8KitDnH
      use_name_instead_of_uri: false
    - name: Michael Rubino
      uri: spotify:artist:2z5VO4bjdr8m2yQvAJxv2T
      use_name_instead_of_uri: false
    - name: Danail Getz
      uri: spotify:artist:2lUhbLKIUctoYVcxyHvMXz
      use_name_instead_of_uri: false
    - name: John A. Graves
      uri: spotify:artist:0iQ9S7yZFZsOdDQhVadnng
      use_name_instead_of_uri: false
    - name: Epic Score
      uri: spotify:artist:4Kyb02r7dR3H1PH7pYkb8X
      use_name_instead_of_uri: false
    - name: Bear McCreary
      uri: spotify:artist:2ifvIECHAlEgPMBuBOJ0lG
      use_name_instead_of_uri: false
    - name: Matt Foundling
      uri: spotify:artist:5cNOqF8KnR5vuaC1VaiUYZ
      use_name_instead_of_uri: false
    - name: Hannu Honkonen
      uri: spotify:artist:2tnlGPezGL8qXqpWuDEtK1
      use_name_instead_of_uri: false
    - name: Calum MacDonald
      uri: spotify:artist:3YH7LtyaHEKHSuJZE4pj13
      use_name_instead_of_uri: false
    - name: Steven Coltart
      uri: spotify:artist:1UyKp5VC9ca2m2K4jChAdS
      use_name_instead_of_uri: false
    - name: Dorian Charnis
      uri: spotify:artist:2ggEvTTbWnTnUDQWtQQGz5
      use_name_instead_of_uri: false
    - name: Frederick Kron
      uri: spotify:artist:0S53WjBCfEVU42YS71QABs
      use_name_instead_of_uri: false
    - name: Boris Nonte
      uri: spotify:artist:3EvnDQ9GqimRR7VXVPRAw4
      use_name_instead_of_uri: false
    - name: Alan Lazar
      uri: spotify:artist:2KBvG7DrYyUZ9gMUeVBmf5
      use_name_instead_of_uri: false
    - name: Matt Mariano
      uri: spotify:artist:7mbe5kbfKi8mIuYlHtQleA
      use_name_instead_of_uri: false
    - name: Alexander Hitchens
      uri: spotify:artist:3XH9T7Jqa3ckEl6vsrYde9
      use_name_instead_of_uri: false
    - name: Joel Steudler
      uri: spotify:artist:1p7BMCpa2YWrf5rSHsmDPJ
      use_name_instead_of_uri: false
    - name: Sami Matar
      uri: spotify:artist:7ijAT5OUQFiBr68fogQHx1
      use_name_instead_of_uri: false
    - name: Twin Flame Music
      uri: spotify:artist:0ZxJQt1K2J3vKB288RUMtb
      use_name_instead_of_uri: false
    - name: Carlos Viola
      uri: spotify:artist:5t8oeNB7ScFOsV5Jkr0EtE
      use_name_instead_of_uri: false
    - name: Danail Getz
      uri: spotify:artist:75FOgzCtGqwMDMJa5IKwGQ
      use_name_instead_of_uri: false
    - name: Steffan Michael Koch
      uri: spotify:artist:7HsxIDeQLlTuZutsr02t7K
      use_name_instead_of_uri: false
    - name: Alex Roe
      uri: spotify:artist:53W9D87UNHesXxzLUEOQix
      use_name_instead_of_uri: false
    - name: Samuel Kim
      uri: spotify:artist:2bdcBjvuI9worc472GbeU0
      use_name_instead_of_uri: false
    - name: Mari Samuelsen
      uri: spotify:artist:670EXb4x6t2MAvRvqCixyx
      use_name_instead_of_uri: false
    - name: Heavy Melody
      uri: spotify:artist:3ja6QDv5gPotqQga9OTzee
      use_name_instead_of_uri: false
    - name: Sky Mubs
      uri: spotify:artist:7e9il2eLEwnmzPfDhV6dIZ
      use_name_instead_of_uri: false
    - name: Iliya Zaki
      uri: spotify:artist:7rGHURf1Mz9X7mWX5pRcmw
      use_name_instead_of_uri: false
    - name: Niklas Johansson
      uri: spotify:artist:0xBtGQISRMiAMHQxi9yzfr
      use_name_instead_of_uri: false
    - name: Rok Nardin
      uri: spotify:artist:7ArkPxPSwZoQw5ESuxt4oG
      use_name_instead_of_uri: false
    - name: Kings & Creatures
      uri: spotify:artist:6qRRd4NpTdiSbIYaPw6IgB
      use_name_instead_of_uri: false
    - name: Piotr Musiał
      uri: spotify:artist:4IVoqcr2G4cE9tH7crHsfE
      use_name_instead_of_uri: false
    - name: Crzysnd
      uri: spotify:artist:2dm2COf4vfKD5qPvZzGAcp
      use_name_instead_of_uri: false
    - name: Celestial Aeon Project
      uri: spotify:artist:3erL8NEQbmmOXhO6yyVWxO
      use_name_instead_of_uri: false
    # - name: Danny Rayel
    #   uri: spotify:artist:2hl3icZTtqfZi9dan2wieR
    #   use_name_instead_of_uri: false
    # - name: David Chappell
    #   uri: spotify:artist:6Mcfzo3GqPaurA2tGbdknQ
    #   use_name_instead_of_uri: false
    # - name: Brian Delgado
    #   uri: spotify:artist:0M8cvelZ9VCFmRpJO7qI7t
    #   use_name_instead_of_uri: false
    # - name: Hyun
    #   uri: spotify:artist:2dzHrGUsgXjZtCQIfvS4T2
    #   use_name_instead_of_uri: false
    # - name: Armin Gutjahr
    #   uri: spotify:artist:7LifGjWrTpbdhn16Gzd9zw
    #   use_name_instead_of_uri: false
    # - name: Christoffer Isefält
    #   uri: spotify:artist:1joXfPc9C7yeMzqaI3O4zK
    #   use_name_instead_of_uri: false
    # - name: Lisa Van Hal
    #   uri: spotify:artist:1uXhewhO51dPbq6V7Bt1bl
    #   use_name_instead_of_uri: false
    # - name: Pieces of Eden
    #   uri: spotify:artist:5yErkGuBsYRvZDllqkfKnD
    #   use_name_instead_of_uri: false
    # - name: Akshay sreeram
    #   uri: spotify:artist:01hKXqjtfYQWrpa2CXIKim
    #   use_name_instead_of_uri: false
    # - name: Bob Dedes
    #   uri: spotify:artist:1NmVLcYTb3CFmYUUjVxsJa
    #   use_name_instead_of_uri: false
    # - name: Craig Meier
    #   uri: spotify:artist:3eXGPiVdy3xJTjSl4QRNlH
    #   use_name_instead_of_uri: false
    # - name: Eduardo Jimenez
    #   uri: spotify:artist:1T0zmRJOXUBIWpnlZDeftM
    #   use_name_instead_of_uri: false
    # - name: Jannick Damkvist
    #   uri: spotify:artist:3NOc12wZVL56uydcyFX23N
    #   use_name_instead_of_uri: false
    # - name: Fred Texier
    #   uri: spotify:artist:1N5Fzr8kzrFVJKgcnqS1sB
      # use_name_instead_of_uri: false
    - name: Iavor Pachovski
      uri: spotify:artist:4bAl3cSPVS8kI4lDazRDTv
      use_name_instead_of_uri: false
    - name: Emad Yaghoubi
      uri: spotify:artist:6mFg0fYWk7PWKigJrLz0Tt
      use_name_instead_of_uri: false
    - name: Samarth Bellur
      uri: spotify:artist:1SQgzWJngOeeXladS7db7x
      use_name_instead_of_uri: false
    - name: Narek Mirzaei
      uri: spotify:artist:4JqQJwLWgKICPfw5hdQTNp
      use_name_instead_of_uri: false
    - name: NINJA TRACKS
      uri: spotify:artist:6528Ex7vvaNcKo87nHri44
      use_name_instead_of_uri: false
    # - name: Tony Delaney
    #   uri: spotify:artist:1ENO3LKcqpRE9fTCSSyfFZ
    #   use_name_instead_of_uri: false
    # - name: Simon Finley
    #   uri: spotify:artist:3ZEjU2D2w0JnANHfgzxLa7
    #   use_name_instead_of_uri: false
    # - name: Benjamin T. Jackson
    #   uri: spotify:artist:0Dk0JOUUbZGlGJdIvMCR1P
    #   use_name_instead_of_uri: false
    # - name: Gareth Thomas
    #   uri: spotify:artist:0527zLnjjuLbpcyUt02sUu
    #   use_name_instead_of_uri: false
    # - name: Hugo Paulo
    #   uri: spotify:artist:6Mwuz2h3uAoZTdVBEKAwgM
    #   use_name_instead_of_uri: false
    # - name: Martin Hataš
    #   uri: spotify:artist:4dju3cCo2ooX9tpRBIMqTt
    #   use_name_instead_of_uri: false
    # - name: Alexandros Nikolaidis
    #   uri: spotify:artist:2RcZ5gYvO4sWo0WlO27tdn
    #   use_name_instead_of_uri: false
    # - name: Steve Syz
    #   uri: spotify:artist:6EzKkOj4Eh29apQOBs2EIS
    #   use_name_instead_of_uri: false
    # - name: Greg Mahaud
    #   uri: spotify:artist:07kxR67V6Qg9VpaLtseRQY
    #   use_name_instead_of_uri: false
    # - name: Christopher Salt
    #   uri: spotify:artist:3G45JPk1rBmg7zMq9jqTC2
    #   use_name_instead_of_uri: false
    # - name: Ruth Barrett
    #   uri: spotify:artist:48ZoDch2iKE7FZEYY67DPB
    #   use_name_instead_of_uri: false
    # - name: Adam Burns
    #   uri: spotify:artist:6zWFATqO3v0esXqDUis3WP
    #   use_name_instead_of_uri: false
    # - name: Alexander Rudd
    #   uri: spotify:artist:02byKbTE2ZyrjUjT6uiTc0
    #   use_name_instead_of_uri: false
    # - name: John Rowcroft
    #   uri: spotify:artist:7GyrVlX5jFlHisEa2X2GSF
    #   use_name_instead_of_uri: false
    # - name: James Copperthwaite
    #   uri: spotify:artist:5eJVBynWXdVYZfxeER5gqQ
    #   use_name_instead_of_uri: false
    # - name: John Cameron
    #   uri: spotify:artist:18ouJo7j7egCFOsRdCTcUk
    #   use_name_instead_of_uri: false
    # - name: Rick Wentworth
    #   uri: spotify:artist:077eXvvPhiwSn9Qc9TvCRk
    #   use_name_instead_of_uri: false
    # - name: Ian Livingstone
    #   uri: spotify:artist:71wbvQyh0QbofdrRXCagLU
    #   use_name_instead_of_uri: false
    # - name: Ethan Livingstone
    #   uri: spotify:artist:5SWVyhFS5ykl0LpJQNNL6H
    #   use_name_instead_of_uri: false
    # - name: Alan Jay Reed
    #   uri: spotify:artist:2hqj7UHtQBI9xqKWOceeeL
    #   use_name_instead_of_uri: false
      # ignored_albums:
      # - name: "Example"
      #   uri: spotify:playlist:2qvP9yerCZCS0U1gZU8wYp
      # - name: "Example"
      #   uri: spotify:playlist:2qvP9yerCZCS0U1gZU8wYp
      # - name: "Example"
      #   uri: spotify:playlist:2qvP9yerCZCS0U1gZU8wYp
  - name: "Epic - Best - in bulk"  # Non used data, just for you
    uri: spotify:playlist:4Q1qSPJr6znaF6nycaQjZh 
    artists:
    - name: Mark John Petrie
      uri: spotify:artist:4Ncm52J5comDoZyE1AJRC9
      use_name_instead_of_uri: false
    - name: Hidden Citizens
      uri: spotify:artist:707cnVfI3ISM4j5uzfTc7J
      use_name_instead_of_uri: false
    - name: Mark Petrie
      uri: spotify:artist:1JmpYoOoDOGPw3uUyqj9m6
      use_name_instead_of_uri: false
    - name: Elephant Music
      uri: spotify:artist:3yiExVtDyEIWLGZSP1r3Vm
      use_name_instead_of_uri: false
    - name: Efisio Cross
      uri: spotify:artist:4AeQ7Pcq0mxxRuKjxDtvCk
      use_name_instead_of_uri: false
    - name: Thomas Bergersen
      uri: spotify:artist:6BF0bXbsdujMSMeFZBGcBq
      use_name_instead_of_uri: false
    - name: Nick Phoenix
      uri: spotify:artist:3EvzCyNmY3kbUkMawjsndF
      use_name_instead_of_uri: false
    - name: Two Steps from Hell
      uri: spotify:artist:2qvP9yerCZCS0U1gZU8wYp
      use_name_instead_of_uri: false
    - name: Future World Music
      uri: spotify:artist:6gmhrHojnyp0SfG4WwJgIE
      use_name_instead_of_uri: false
    - name: Dos Brains
      uri: spotify:artist:2m1jyLK9kufk4DasfhR0Qa
      use_name_instead_of_uri: false
    - name: Audiomachine
      uri: spotify:artist:5F4ObszoeVebqtc0B3XqJa
      use_name_instead_of_uri: false
    - name: Marcus Warner
      uri: spotify:artist:44HQ4cmv8MKMNHkPtXwZbQ
      use_name_instead_of_uri: false
    - name: Imagine Music
      uri: spotify:artist:4SOk9hgrKvDv8pVI1iUZ8L
      use_name_instead_of_uri: false
    - name: James Dooley
      uri: spotify:artist:1ZHio9RIhXSROw2pqxiZ91
      use_name_instead_of_uri: false
    - name: Really Slow Motion
      uri: spotify:artist:4dDb2XLONSNrTrucRcoaYM
      use_name_instead_of_uri: false
    - name: Instrumental Core
      uri: spotify:artist:0aVtz2xOAWpDgiTS6k2rDN
      use_name_instead_of_uri: false
    - name: Immediate
      uri: spotify:artist:5RcJDMYwS4w1XJkNiR4LvM
      use_name_instead_of_uri: false
DEBUG: true

